services:
  - type: web
    name: gestion-conges-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://postgres:yasmine2026%2Fprojet@db.ahavhwdridkzubwtjmuu.supabase.co:5432/postgres
      # Remove SPRING_DATASOURCE_USERNAME and SPRING_DATASOURCE_PASSWORD entirely
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000