services:
  - type: web
    name: gestion-conges-backend
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://postgres:yasmine2026/projet@db.ahavhwdridkzubwtjmuu.supabase.co:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: yasmine2026/projet